trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Sondor.ResultManager/**

pool:
  vmImage: windows-latest

variables:
- name: major
  value: 1
- name: minor
  value: 1
- name: repository
  value: sondor-result-manager-package
- group: sondor-git
- group: sondor-nuget

resources:
  repositories:
    - repository: templates
      type: git
      name: sondor-pipeline-templates
      ref: master

steps:
- template: package-publish.yml@templates
  parameters:
    nuGetFeedType: 'external'
    repository: ${{ variables.repository }}
    feed: ''